global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: atlas-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000
        labels:
          service: atlas-api
          env: development

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
