apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlas.fullname" . }}-secrets
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  ATLAS_SECRET_KEY: {{ .Values.secrets.atlasSecretKey | quote }}
